### ISSUE TITLE
Make EffectCommand & GamemodeCommand compatible with Minecraft 1.13 and more newer ! :)

### ISSUE THREAD

**Issue by KeyKatyu** [MrGraversen/minecraft-rcon#3]
Hi,
I openned this issue to ask if it would be possible to make the RCON "EffectCommand" and "GamemodeCommand" functions compatible with the new arguments of these.  (Examples: /effect GIVE [Player] [Effect] [Time] [Amplifier] [HideParticles] and /effect CLEAR [Player]).

**Comment by MrGraversen** [comment]
Thanks for letting me know, I will work in a fix for this

**Comment by KeyKatyu** [comment]
Do you now when ?
