### ISSUE TITLE
Can't connect after a failed connection

### ISSUE THREAD

**Issue by 2000Slash** [MrGraversen/minecraft-rcon#4]
I recently ran into the problem, that you can't reconnect after a failed connection. This is because on a failed connection, the executorService of the MinecraftRconService is shut down (safeClose() in MinecrtaftRconService is called). Is this by design? I think it would be better to only shut down the executorService when it is never needed again.

**Comment by MrGraversen** [comment]
Hi! Sorry for the (very) late reply.

I'm assuming this happens after exhausted retry attempts, after which the service assumes that further attempting is futile.

When running this project on my own servers, I usually set retry limit to infinite (`Integer.MAX_VALUE`), which allows me to update the Minecraft server, stop it and perform maintenance, etc., without it causing trouble for the RCON client.

**Comment by 2000Slash** [comment]
No Problem! Thanks for the tip, I think this should fix it.
