### ISSUE TITLE
Can't send Tellraw command.

### ISSUE THREAD

**Issue by Neutron-Pro** [MrGraversen/minecraft-rcon#6]
Hi,

I have encountered a problem with the Tellraw command (This must be present for the other commands too).

I can't send the command because GSON doesn't read the final private fields.

Did I forget to implement something or is it a bug ?

```
java.lang.AssertionError: java.lang.IllegalAccessException: class com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1 cannot access a member of class io.graversen.minecraft.rcon.commands.tellraw.TellRawCommand with modifiers "private final"
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:249)
        at com.google.gson.Gson.toJson(Gson.java:703)
        at com.google.gson.Gson.toJson(Gson.java:682)
        at com.google.gson.Gson.toJson(Gson.java:637)
        at com.google.gson.Gson.toJson(Gson.java:617)
        at io.graversen.minecraft.rcon.JsonUtils.toJson(JsonUtils.java:10)
        at io.graversen.minecraft.rcon.commands.tellraw.TellRawCommand.command(TellRawCommand.java:107)
        at io.graversen.minecraft.rcon.MinecraftRcon.sendAsync(MinecraftRcon.java:31)
```

**Comment by MrGraversen** [comment]
Hey,

That's strange. GSON, under normal circumstances, has no problem serializing from immutable fields, unless a specific GSON configuration is used, for example to include only fields marked with `@Exposed` or similar. However, this is not the case for this project.

Are you by any chance using the Java Module System? Which JDK are you using?

The GSON configuration used by this project is simple:

```java
public class JsonUtils {
    private static final Gson GSON_INSTANCE = new GsonBuilder().disableHtmlEscaping().create();

    public static String toJson(Object object) {
        return GSON_INSTANCE.toJson(object);
    }
}
```

The following code works under `openjdk 11.0.9.1`:

```java
final var tellRawCommand = new TellRawCommandBuilder()
        .targeting(Selectors.ALL_PLAYERS)
        .withText("This should work!")
        .italic()
        .withColor(Colors.RED)
        .build();

System.out.println(tellRawCommand.command());
```

Outputs: 

```
tellraw @a {"text":"This should work!","bold":false,"italic":true,"underlined":false,"striketrough":false,"obfuscated":false,"color":"red"}
```

**Comment by Neutron-Pro** [comment]
I use the JDK 16. Maybe this is not yet compatible ?

I see in your answer that it is probably the JDK 11. I will test it.


[EDIT]
I have upgraded to JDK version 11 and there are no more problems. 

Thank you and good luck, I really appreciate the work done on this project.
