### ISSUE TITLE
java 8

### ISSUE THREAD

**Issue by RumoEL** [MrGraversen/minecraft-rcon#7]
if possible, make for java 8 version

**Comment by MrGraversen** [comment]
Hi @RumoEL. What is the reason you need a Java 8 version? Java 11 is the latest LTS.

**Comment by RumoEL** [comment]
the server on which the server is running uses java 8, I cannot change the startup line.
(chmod rwx r-x r-- file.sh, another user)

**Comment by MrGraversen** [comment]
OK, that sounds strange. Although I guess with the release of Minecraft 1.17 you've been forced to upgrade to JRE 16 by now? 😄

**Comment by RumoEL** [comment]
the question is resolved for me because the admin is transferring the server to 1.17.
